In [ ]:
import numpy as np

In [ ]:
mylist = [1,2,3]

In [3]:
np.array(mylist)

array([1, 2, 3])

In [4]:
nested_list = [[1,2],[3,4],[5,6]]

In [5]:
np.array(nested_list)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [6]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [7]:
np.zeros(3)

array([0., 0., 0.])

In [8]:
np.zeros((4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [9]:
np.ones(3)

array([1., 1., 1.])

In [10]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
np.linspace(0,10,21)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
np.random.rand(2)

array([0.70123293, 0.68031518])

In [14]:
np.random.rand(3,4)

array([[0.4638878 , 0.76096183, 0.04640327, 0.56926653],
       [0.78031531, 0.55672512, 0.36223884, 0.15328797],
       [0.64223258, 0.44502352, 0.63014305, 0.91672586]])

In [15]:
np.random.randn(5,5)

array([[-0.42320805, -0.72060743,  2.62846227, -2.32032736,  0.28524572],
       [ 0.05959517, -2.20980481,  0.05366818,  1.3279982 , -0.43767965],
       [ 0.57361914,  0.01485702,  0.74443373, -0.02974798, -0.89963619],
       [-0.40632237, -0.16447681, -0.02755571,  0.0291424 , -0.52027609],
       [-0.58274734,  0.24248238,  0.88821178,  0.82649702,  0.1018193 ]])

In [16]:
np.random.randint(1,100, (2,3)) #e.g. simulate people's ages by groups

array([[46, 36, 45],
       [ 2, 24, 22]])

In [27]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [28]:
np.random.rand(4)

array([0.15601864, 0.15599452, 0.05808361, 0.86617615])

In [29]:
arr = np.arange(25)

In [30]:
ranarr = np.random.randint(0,50,10)

In [31]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [32]:
ranarr

array([35, 39, 23,  2, 21,  1, 23, 43, 29, 37])

In [33]:
arr.shape

(25,)

In [38]:
arr = arr.reshape(5,5) #you have to reshape to exact count in the array

In [39]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [40]:
ranarr

array([35, 39, 23,  2, 21,  1, 23, 43, 29, 37])

In [41]:
ranarr.max()

43

In [44]:
ranarr.argmax()

7

In [45]:
ranarr.min()

1

In [46]:
ranarr.argmin()

5

In [47]:
ranarr.dtype

dtype('int64')

In [51]:
myarr = np.random.rand(4)

In [52]:
myarr.dtype

dtype('float64')

# Numpy Index Selection

In [53]:
arr = np.arange(0,11)

In [54]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [55]:
arr[8]

8

In [56]:
arr[1:5]

array([1, 2, 3, 4])

In [57]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [58]:
arr[:5]

array([0, 1, 2, 3, 4])

In [59]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [63]:
#broadcasting (reassignment) of numbers

In [64]:
arr[0:5]=100

In [65]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [66]:
arr = np.arange(0,11)

In [67]:
slice_of_arr = arr[0:5]

In [68]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [69]:
slice_of_arr[:]=99

In [71]:
slice_of_arr #broadcasting--> reassignment

array([99, 99, 99, 99, 99])

In [73]:
arr #you'll notice that the prev line as affected the original array

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [84]:
arr_copy = arr.copy() #make a copy instead to not make any changes to the original array

In [85]:
arr_copy[:]= 100

In [86]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [87]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [89]:
arr_2d = np.array([[5,10,15], [20,25,30], [35,40,45]])

In [90]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [92]:
arr_2d.shape #returns # of rows, then # of columns

(3, 3)

In [97]:
arr_2d[1][1] #or arr_2d[1,1]

25

In [98]:
arr_2d[0,2]

15

In [101]:
arr_2d[:2,1:] #won't see that often with real datasets 

array([[10, 15],
       [25, 30]])

In [105]:
arr = np.arange(3,11)

In [106]:
arr

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [107]:
arr > 4  #choosing the numbers that are greater than 4

array([False, False,  True,  True,  True,  True,  True,  True])

In [108]:
bool_arr = arr>4

In [109]:
bool_arr

array([False, False,  True,  True,  True,  True,  True,  True])

In [113]:
arr[bool_arr] #will only choose the "True"

array([ 5,  6,  7,  8,  9, 10])

In [114]:
arr[arr>4] #another way of writing it short-handedly

array([ 5,  6,  7,  8,  9, 10])