In [9]:
import numpy as np

##  Arithmetic Operations

In [21]:
arr = np.arange(0,10)

In [22]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
arr + 5 #perform this operation on an element by element basis

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [24]:
arr -2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [25]:
arr + arr #add it to itself

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [26]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [27]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
arr_copy=arr.copy()

In [30]:
arr_copy[:]=99

In [31]:
arr_copy

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [34]:
arr #you will notice that although arr_copy has been altered, original list, arr has not

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [36]:
arr/arr

<ipython-input-36-50b4ced5627e>:1: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [37]:
1/0

ZeroDivisionError: division by zero

In [40]:
1 / arr #if u have something being divided by 1, you will get a warning, but still get a result, either by nan or inf

<ipython-input-40-e21ee5523ef5>:1: RuntimeWarning: divide by zero encountered in true_divide
  1 / arr #if u have something being divided by 1, you will get a warning, but still get a result, either by nan or inf


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [41]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [42]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [44]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [45]:
np.log(arr)

<ipython-input-45-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

## Summary Stats

In [46]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
arr.sum()

45

In [48]:
arr.mean()

4.5

In [49]:
arr.max()

9

In [53]:
arr.var()

8.25

In [54]:
arr.std()

2.8722813232690143

In [68]:
arr2d = np.arange(0,25).reshape(5,5)

In [69]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [70]:
arr2d.sum()

300

In [71]:
arr2d.sum(axis=0) #axis = 0 is finding the sum ACROSS the rows, which seems that they are being added down the columns

array([50, 55, 60, 65, 70])

In [72]:
arr2d.sum(axis=1) #perform this operation across the columns

array([ 10,  35,  60,  85, 110])

In [75]:
arr2d.shape #axis= 0 is across rows, axis = 1 is across columns, they might seem as if they should be switched, but the key word is across

(5, 5)

In [76]:
arr2d.sum(axis=1)

array([ 10,  35,  60,  85, 110])

# NumPy Exercises

1. Import Numpy as np

In [79]:
import numpy as np

2. Create an array of 10 zeros

In [88]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create an array of 10 fives

In [94]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [95]:
arr = np.ones(10)

In [93]:
arr*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

4. Create an array of the integers from 10 to 50

In [96]:
arr = np.arange(10,51)

In [97]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

5. Create an array of all the even integers from 10 to 50

In [98]:
arr = np.arange(10,51,2)

In [99]:
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [101]:
arr = np.arange(0,9)

6. Create a 3x3 matrix with values ranging form 0 to 8

In [105]:
arr.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

7. Create a 3x3 identity matrix

In [109]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

8. Generate a random number between 0 and 1

In [114]:
np.random.rand(1)

array([0.39967987])

10. Generate an array of 25 random numbers sampled from a standard normal distribution

In [117]:
np.random.randn(25)

array([-2.27025978, -0.26677406, -0.23112327,  1.94096516, -0.27030431,
        0.66307158,  0.85974356, -3.30171386,  0.77289837, -0.90295074,
       -0.14422759,  1.26790987, -0.25980097, -1.16958114,  0.09759119,
        0.46723023, -0.23110183, -0.50313441, -0.68224704,  0.33134695,
       -1.15540085, -1.8938908 ,  0.50142678, -0.38072025, -0.39276167])

11. Create the following matrix

In [155]:
arr = np.arange(1,101)/100
arr.reshape (10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

12. Create an array of 20 linearly spaced integers

In [157]:
np.linspace(0,1,20) #20 points, linearly spaced

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

# Numpy Index and Selection

In [158]:
mat = np.arange(1,26).reshape(5,5)

In [159]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [161]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [162]:
mat[3,4]

20

In [166]:
 mat[:3,1:2] #have to use slicing to retain the 2d shape

array([[ 2],
       [ 7],
       [12]])

In [169]:
mat[4]

array([21, 22, 23, 24, 25])

In [170]:
mat.sum()

325

In [171]:
mat.std()

7.211102550927978

In [172]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

In [180]:
np.random.seed(101)
np.random.rand(1)

array([0.51639863])